// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOKpBCoOKVbtYmKIjWja_uyOIxkSg_FL0',
    appId: '1:638955132197:web:28de2c9a565549737536cc',
    messagingSenderId: '638955132197',
    projectId: 'grampanchayat-64901',
    authDomain: 'grampanchayat-64901.firebaseapp.com',
    storageBucket: 'grampanchayat-64901.firebasestorage.app',
    measurementId: 'G-LE88QEV1YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVdXRM9rQdMmIgkplfiTTK68nlZDIMOTc',
    appId: '1:638955132197:android:dbc733119dff10cd7536cc',
    messagingSenderId: '638955132197',
    projectId: 'grampanchayat-64901',
    storageBucket: 'grampanchayat-64901.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDkbSY1wilXgqUGjOp2opnEFakVXqOiRA',
    appId: '1:638955132197:ios:2feb367bd4a3f0d27536cc',
    messagingSenderId: '638955132197',
    projectId: 'grampanchayat-64901',
    storageBucket: 'grampanchayat-64901.firebasestorage.app',
    iosBundleId: 'com.example.grampanchayatAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDkbSY1wilXgqUGjOp2opnEFakVXqOiRA',
    appId: '1:638955132197:ios:2feb367bd4a3f0d27536cc',
    messagingSenderId: '638955132197',
    projectId: 'grampanchayat-64901',
    storageBucket: 'grampanchayat-64901.firebasestorage.app',
    iosBundleId: 'com.example.grampanchayatAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOKpBCoOKVbtYmKIjWja_uyOIxkSg_FL0',
    appId: '1:638955132197:web:a84c3a6f859434d97536cc',
    messagingSenderId: '638955132197',
    projectId: 'grampanchayat-64901',
    authDomain: 'grampanchayat-64901.firebaseapp.com',
    storageBucket: 'grampanchayat-64901.firebasestorage.app',
    measurementId: 'G-2YFRY0J2CX',
  );

}